#!/bin/bash
# based on https://gist.github.com/yellowled/1439610

IN=$1

OUT=$2

# webm
ffmpeg -i $IN -vcodec libvpx-vp9 -b:v 1M -an $OUT.web.webm
#ffmpeg -i $IN -f webm -vcodec libvpx -an -ab 128000 -crf 22 -s $Wx$H $OUT.web.webm

# mp4
ffmpeg -i $IN -vcodec h264 -an -strict -2 $OUT.web.mp4
#ffmpeg -i $IN -an -strict experimental -ac 2 -ab 128k -vcodec libx264 -vpre slow -f mp4 -crf 22 -profile:v baseline -level 3 -s $Wx$H $OUT.web.mp4

